strictness: high
test-warnings: true
doc-warnings: false

pylint:
  disable:
    - no-self-argument
    - super-init-not-called
    - unsubscriptable-object
    - broad-exception-raised

pycodestyle:
  disable:
    - N805

mccabe:
  run: true