version: '3'

services:
  backend:
    container_name: fastapi_mongodb_backend
    build: .
    depends_on:
      - database
    ports:
      - '8000:8000'
    networks:
      - fastapi_mongodb

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - fastapi_mongodb

networks:
  fastapi_mongodb:
    driver: bridge

volumes:
  data: